# Generated by Django 5.2 on 2025-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tick_id', models.IntegerField(unique=True)),
                ('product_code', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
                ('best_bid', models.FloatField()),
                ('best_ask', models.FloatField()),
                ('best_bid_size', models.FloatField()),
                ('best_ask_size', models.FloatField()),
                ('total_bid_depth', models.FloatField()),
                ('total_ask_depth', models.FloatField()),
                ('market_bid_size', models.FloatField()),
                ('market_ask_size', models.FloatField()),
                ('ltp', models.FloatField()),
                ('volume', models.FloatField()),
                ('volume_by_product', models.FloatField()),
            ],
            options={
                'db_table': 'tickers',
            },
        ),
    ]
