version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "7000:7000"
    depends_on:
      - db
    environment:
      - DJANGO_ENV=production
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-mysql_api_production}
      - DB_USER=${DB_USER:-production_user}
      - DB_PASSWORD=${DB_PASSWORD:-production_password}
      - DB_PORT=3307
      - SECRET_KEY=${SECRET_KEY:-production-secret-key-change-this-to-a-secure-value}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
    volumes:
      - static_volume:/app/static
    networks:
      - app_network

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME:-mysql_api_production}
      - MYSQL_USER=${DB_USER:-production_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-production_password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
  static_volume:

networks:
  app_network:
