name: Django Tests

on:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: mysql_api_local
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd python/drf
        pip install -r requirements.txt

    - name: Create test environment file
      run: |
        cd python/drf
        mkdir -p env/local
        cat > env/local/.env << 'EOL'
        # テスト環境用の設定
        DEBUG=True
        SECRET_KEY=django-insecure-b525gig#ci$vp0rg#$w95hzi^a8u7s2fldl93=7xf7s=j#8bhf
        ALLOWED_HOSTS=localhost,127.0.0.1

        # データベース設定
        DB_NAME=mysql_api_local
        DB_USER=root
        DB_PASSWORD=
        DB_HOST=localhost
        DB_PORT=3306
        EOL

    - name: Run tests
      run: |
        cd python/drf
        python manage.py test
      env:
        DJANGO_ENV: development
