name: Golang Tests

on:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  test:
    name: Test Golang Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./golang

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...

      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: go mod tidy diff
        run: |
          go mod tidy
          git diff --exit-code

      - name: Run tests
        run: go test -v ./...
